nodeLinker: pnp

packageExtensions:
  eslint-config-next@*:
    dependencies:
      next: "*"
  eslint-plugin-prettier@*:
    dependencies:
      eslint-config-prettier: "*"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
