name: Refactoring
description: 리팩토링 작업을 요청합니다
labels: ["refactor"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: 리팩토링 대상 영역을 선택하세요
      options:
        - client
        - server
        - workspace
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: 왜 리팩토링이 필요한가?
      placeholder: |
        - 기술 부채: ...
        - 유지보수성 문제: ...
        - 성능 문제: ...
    validations:
      required: true
  - type: textarea
    id: improvement
    attributes:
      label: Improvement
      description: 어떻게 개선할 것인가?
      placeholder: |
        - Before: ...
        - After: ...
        - 예상 효과: ...
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: 변경될 파일, 모듈, 경로를 적어 주세요.
      placeholder: |
        - 파일: src/...
        - 모듈: ...
    validations:
      required: true
  - type: textarea
    id: done
    attributes:
      label: Definition of Done
      description: 리팩토링 완료를 확인할 수 있는 조건을 작성해 주세요.
      placeholder: |
        - [ ] 기존 기능 정상 동작 확인
        - [ ] 관련 테스트 통과
        - [ ] 코드 리뷰 완료
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: 이 작업 전에 먼저 완료되어야 하는 선행 Issue를 작성해 주세요. 없으면 "없음"으로 작성합니다.
      placeholder: |
        - #123 (설명)
        - #456 (설명)

        선행 작업이 없으면: 없음
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: 리팩토링의 중요도를 선택하세요
      options:
        - "priority:0 — Critical (즉시 대응)"
        - "priority:1 — High (가능한 빨리)"
        - "priority:2 — Medium (일반)"
        - "priority:3 — Low (여유)"
        - "priority:4 — Backlog (나중에)"
      default: 2
    validations:
      required: true
